In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
from google.colab import drive

In [4]:
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
data = pd.read_csv('/content/drive/MyDrive/Spam_Mail_Detection/spam_ham_dataset.csv')

In [7]:
data

text  spam
0     Subject: enron methanol ; meter # : 988291\r\n...     0
1     Subject: hpl nom for january 9 , 2001\r\n( see...     0
2     Subject: neon retreat\r\nho ho ho , we ' re ar...     0
3     Subject: photoshop , windows , office . cheap ...     1
4     Subject: re : indian springs\r\nthis deal is t...     0
...                                                 ...   ...
5166  Subject: put the 10 on the ft\r\nthe transport...     0
5167  Subject: 3 / 4 / 2000 and following noms\r\nhp...     0
5168  Subject: calpine daily gas nomination\r\n>\r\n...     0
5169  Subject: industrial worksheets for august 2000...     0
5170  Subject: important online banking alert\r\ndea...     1

[5171 rows x 2 columns]

In [8]:
data['spam'].value_counts()

0    3672
1    1499
Name: spam, dtype: int64

In [10]:
data.drop_duplicates(inplace=True)

In [11]:
data

text  spam
0     Subject: enron methanol ; meter # : 988291\r\n...     0
1     Subject: hpl nom for january 9 , 2001\r\n( see...     0
2     Subject: neon retreat\r\nho ho ho , we ' re ar...     0
3     Subject: photoshop , windows , office . cheap ...     1
4     Subject: re : indian springs\r\nthis deal is t...     0
...                                                 ...   ...
5165  Subject: fw : crosstex energy , driscoll ranch...     0
5166  Subject: put the 10 on the ft\r\nthe transport...     0
5167  Subject: 3 / 4 / 2000 and following noms\r\nhp...     0
5169  Subject: industrial worksheets for august 2000...     0
5170  Subject: important online banking alert\r\ndea...     1

[4993 rows x 2 columns]

In [14]:
data['spam'].value_counts()

0    3531
1    1462
Name: spam, dtype: int64

In [15]:
#TO check null value
data.isnull().sum()

text    0
spam    0
dtype: int64

In [16]:
# Separate x and y
x = data.text.values
y = data.spam.values

In [18]:
#split dataset
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2)

In [19]:
#Data Preprocessing
from sklearn.feature_extraction.text import CountVectorizer


In [20]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [21]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
from sklearn.naive_bayes import MultinomialNB

In [23]:
model = MultinomialNB()
model.fit(x_train, ytrain)

MultinomialNB()

In [24]:
#Again Data transform using countvectorizer
x_test = cv.transform(xtest)

In [25]:
#To see x_test Data
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [5, 7, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [26]:
# TO see Accuracy
model.score(x_test, ytest)

0.9819819819819819

In [28]:
# TO check email
emails = ['hey i am looking for machine learning Linear regression model','hey you win laptop, please click our link']


In [29]:
#Data Preposessing
cv_emails = cv.transform(emails)

In [30]:
#Prediction from this two mail
model.predict(cv_emails)

array([0, 1])

In [31]:
#Performace Calculation

pred = model.predict(x_test)

In [32]:
pred

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
#To accuracy from test data
accuracy_score(ytest, pred)

0.9819819819819819

In [35]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(ytest, pred)

array([[702,  10],
       [  8, 279]])

In [37]:
# To see Classification Report
from sklearn.metrics import classification_report

In [41]:
print(classification_report(ytest, pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       712
           1       0.97      0.97      0.97       287

    accuracy                           0.98       999
   macro avg       0.98      0.98      0.98       999
weighted avg       0.98      0.98      0.98       999

